import { and, asc, desc, eq, like, or, sql, type SQL } from "drizzle-orm";
import { getDb } from "../../../../db";
import { applications, clubs, teacherClubs, users } from "../../../../db/schema";
import { isApplicationStatus } from "../../../lib/application-admin";
import { clubName } from "../../../lib/clubs";
import { requireUser, sanitizeText } from "../../../lib/security";

export async function GET(request:Request){const auth=await requireUser(["club_manager"]);if("error" in auth)return auth.error;const p=new URL(request.url).searchParams,page=pos(p.get("page"),1),pageSize=Math.min(100,pos(p.get("pageSize"),20)),status=p.get("status")??"",clubId=sanitizeText(p.get("clubId"),80),search=sanitizeText(p.get("search"),200),sort=p.get("sort")==="oldest"?"oldest":"newest";if(status&&!isApplicationStatus(status))return Response.json({error:"INVALID_STATUS"},{status:400});const filters:SQL[]=[eq(teacherClubs.teacherUserId,auth.user.id)];const statusFilter=isApplicationStatus(status)?status:null;if(statusFilter)filters.push(eq(applications.status,statusFilter));if(clubId)filters.push(eq(applications.clubId,clubId));if(search){const pattern=`%${search}%`,f=or(like(applications.publicId,pattern),like(users.alias,pattern),like(clubs.name,pattern),like(applications.motivation,pattern));if(f)filters.push(f)}const where=and(...filters),db=getDb(),base=db.select({id:applications.id,applicationNumber:applications.publicId,userAlias:users.alias,clubId:applications.clubId,databaseClubName:clubs.name,status:applications.status,submittedAt:applications.submittedAt,updatedAt:applications.updatedAt,reviewedAt:applications.reviewedAt}).from(applications).innerJoin(teacherClubs,eq(applications.clubId,teacherClubs.clubId)).innerJoin(users,eq(applications.userId,users.id)).leftJoin(clubs,eq(applications.clubId,clubs.id)),countBase=db.select({count:sql<number>`count(*)`}).from(applications).innerJoin(teacherClubs,eq(applications.clubId,teacherClubs.clubId)).innerJoin(users,eq(applications.userId,users.id)).leftJoin(clubs,eq(applications.clubId,clubs.id));const[rows,counts]=await Promise.all([base.where(where).orderBy(sort==="oldest"?asc(applications.submittedAt):desc(applications.submittedAt)).limit(pageSize).offset((page-1)*pageSize),countBase.where(where)]),total=Number(counts[0]?.count??0);return Response.json({applications:rows.map(({databaseClubName,...row})=>({...row,clubName:databaseClubName||clubName(row.clubId)})),pagination:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))}})}
function pos(value:string|null,fallback:number){const n=Number.parseInt(value??"",10);return Number.isFinite(n)&&n>0?n:fallback}
