import { clubName } from "../../../../lib/clubs";
import { writeAudit } from "../../../../lib/database/audit";
import { findAdminQuestion,findQuestionAnswer,updateQuestionDeletion,type AdminQuestionRow } from "../../../../lib/database/questions";
import { checkRateLimit,hasOversizedBody } from "../../../../lib/rate-limit";
import { id,requireUser,sameOrigin } from "../../../../lib/security";

const allowedKeys=new Set(["isDeleted"]);
export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireUser(["admin"]);if("error" in auth)return auth.error;const question=await findAdminQuestion((await params).id);if(!question)return Response.json({error:"NOT_FOUND"},{status:404});const answer=await findQuestionAnswer(question.id);return Response.json({question:camel(question,answer)})}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireUser(["admin"]);if("error" in auth)return auth.error;if(!sameOrigin(request))return Response.json({error:"INVALID_ORIGIN"},{status:403});if(hasOversizedBody(request,1_024))return Response.json({error:"REQUEST_TOO_LARGE"},{status:413});const limited=await checkRateLimit(request,{scope:"admin-question-deletion",identifier:auth.user.id,limit:30,windowMs:60_000});if(limited)return limited;const body=await request.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body)||Object.keys(body).length!==1||Object.keys(body).some(key=>!allowedKeys.has(key))||typeof body.isDeleted!=="boolean")return Response.json({error:"INVALID_FIELDS"},{status:400});const questionId=(await params).id,current=await findAdminQuestion(questionId);if(!current)return Response.json({error:"NOT_FOUND"},{status:404});const wasDeleted=Boolean(current.deleted_at);if(wasDeleted===body.isDeleted){const answer=await findQuestionAnswer(questionId);return Response.json({question:camel(current,answer)})}const now=new Date().toISOString(),updated=await updateQuestionDeletion(questionId,body.isDeleted?now:null,now);if(!updated)return Response.json({error:"NOT_FOUND"},{status:404});await writeAudit({id:id("audit"),actor_user_id:auth.user.id,actor_role:"admin",action_type:body.isDeleted?"qna.question_deleted":"qna.question_restored",target_type:"question",target_id:questionId,before_data:{isDeleted:wasDeleted},after_data:{isDeleted:body.isDeleted},created_at:now});const answer=await findQuestionAnswer(questionId);return Response.json({question:camel(updated,answer)})}
type Answer=Awaited<ReturnType<typeof findQuestionAnswer>>;
function camel(question:AdminQuestionRow,answer:Answer){return{id:question.id,clubId:question.club_id,clubName:clubName(question.club_id),author:"익명",title:question.title,content:question.content,isPrivate:question.is_private,isDeleted:Boolean(question.deleted_at),status:question.status,createdAt:question.created_at,updatedAt:question.updated_at,answer:answer?{content:answer.content,role:answer.author_role==="admin"?"관리자 답변":"담당 교사 답변",createdAt:answer.created_at}:null}}
