"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import PortalShell from "../../../components/PortalShell";

type Application = { id:string; applicationNumber:string; studentName:string|null; studentNumber:string|null; userAlias:string; clubId:string; clubName:string; status:string; motivation:string; interestArea:string|null; careerInterest:string; experience:string; additionalMessage:string|null; submittedAt:string; updatedAt:string; cancelledAt:string|null; reviewedAt:string|null; reviewComment:string|null };
const labels:Record<string,string>={submitted:"신청 완료",under_review:"검토 중",waiting:"대기",approved:"승인",rejected:"반려",cancelled:"취소"};
const nextStates:Record<string,string[]>={submitted:["under_review","approved","rejected"],under_review:["waiting","approved","rejected"],waiting:["approved","rejected"],approved:[],rejected:[],cancelled:[]};

export default function AdminApplicationDetailClient({ applicationId }: { applicationId: string }) {
  const [application,setApplication]=useState<Application|null>(null), [status,setStatus]=useState(""), [reviewComment,setReviewComment]=useState(""), [message,setMessage]=useState(""), [saving,setSaving]=useState(false), [notFound,setNotFound]=useState(false);
  const load=useCallback(async()=>{const response=await fetch(`/api/admin/applications/${applicationId}`,{cache:"no-store"});if(!response.ok){setNotFound(true);return}const item=(await response.json()).application;setApplication(item);setStatus(nextStates[item.status]?.[0]??"");setReviewComment(item.reviewComment??"")},[applicationId]);
  useEffect(()=>{void load()},[load]);
  async function save(){if(!status)return;setSaving(true);setMessage("");try{const response=await fetch(`/api/admin/applications/${applicationId}/status`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status,reviewComment})});const data=await response.json().catch(()=>({}));if(!response.ok){const errors:Record<string,string>={INVALID_STATUS_TRANSITION:"현재 상태에서는 선택한 상태로 변경할 수 없습니다.",APPLICATION_CONFLICT:"다른 관리자가 먼저 변경했습니다. 새로고침 후 다시 시도해 주세요.",REVIEW_COMMENT_TOO_LONG:"검토 의견은 1000자 이하로 작성해 주세요."};setMessage(errors[data.error]??"변경 내용을 저장하지 못했습니다.");return}await load();setMessage("변경 내용을 저장했습니다.")}finally{setSaving(false)}}
  if(notFound)return <PortalShell title="신청 상세 관리" description="신청 내용과 검토 상태를 안전하게 관리합니다."><div className="empty-panel">신청을 찾을 수 없거나 접근 권한이 없습니다.</div></PortalShell>;
  if(!application)return <PortalShell title="신청 상세 관리" description="신청 내용과 검토 상태를 안전하게 관리합니다."><div className="empty-panel">신청을 불러오는 중입니다.</div></PortalShell>;
  return <PortalShell title="신청 상세 관리" description="신청 내용과 검토 상태를 안전하게 관리합니다."><div className="panel application-detail">
    <div className="application-detail-heading admin-applicant-heading"><div><h2>{application.studentNumber&&application.studentName?`${application.studentNumber} ${application.studentName}`:"학생 정보 미등록"}</h2><dl><div><dt>익명 별칭</dt><dd>{application.userAlias}</dd></div><div><dt>신청 번호</dt><dd>{application.applicationNumber}</dd></div><div><dt>동아리</dt><dd>{application.clubName}</dd></div></dl></div><span className={`state state-${application.status}`}>{labels[application.status]??application.status}</span></div>
    <dl className="application-detail-list"><div><dt>지원 동기</dt><dd>{application.motivation}</dd></div><div><dt>관심 분야</dt><dd>{application.interestArea||"작성하지 않음"}</dd></div><div><dt>희망 진로</dt><dd>{application.careerInterest||"작성하지 않음"}</dd></div><div><dt>관련 활동 경험</dt><dd>{application.experience||"작성하지 않음"}</dd></div><div><dt>추가 전달 내용</dt><dd>{application.additionalMessage||"작성하지 않음"}</dd></div><div><dt>제출 시각</dt><dd>{new Date(application.submittedAt).toLocaleString("ko-KR")}</dd></div><div><dt>최근 수정 시각</dt><dd>{new Date(application.updatedAt).toLocaleString("ko-KR")}</dd></div><div><dt>취소 시각</dt><dd>{application.cancelledAt?new Date(application.cancelledAt).toLocaleString("ko-KR"):"-"}</dd></div><div><dt>검토 시각</dt><dd>{application.reviewedAt?new Date(application.reviewedAt).toLocaleString("ko-KR"):"-"}</dd></div></dl>
    <div className="admin-review-form"><label>변경할 상태<select value={status} disabled={!nextStates[application.status]?.length} onChange={event=>setStatus(event.target.value)}>{(nextStates[application.status]??[]).map(value=><option value={value} key={value}>{labels[value]}</option>)}</select></label><label>검토 의견<textarea maxLength={1000} value={reviewComment} onChange={event=>setReviewComment(event.target.value)}/></label>{message&&<p className={message.includes("저장했습니다")?"form-success":"form-error"} role="status">{message}</p>}<div className="button-row"><Link className="secondary link-button" href="/admin/applications">목록으로 돌아가기</Link><button className="primary" disabled={saving||!status} onClick={save}>{saving?"저장 중…":"변경 저장"}</button></div></div>
  </div></PortalShell>;
}
