"use client";

import Link from "next/link";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { HeaderAccount,HeaderSessionProvider } from "../../../components/HeaderSession";
import type{ApplicationAvailability,ClubSource}from"../../../lib/clubs";

const initialForm={motivation:"",interestArea:"",careerInterest:"",experience:"",additionalMessage:"",confirmed:false};
const openStatus=(value:string)=>["모집중","추가모집중","신청가능"].includes(value.replace(/\s+/g,""));
const fieldIcon=(key:"motivation"|"interestArea"|"careerInterest"|"experience"|"additionalMessage")=>{
 if(key==="motivation")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18h6M10 22h4"/><path d="M8.2 14.8A7 7 0 1 1 15.8 14.8c-.8.6-1.3 1.5-1.3 2.2h-5c0-.7-.5-1.6-1.3-2.2Z"/><path d="M12 2v2M4.9 4.9l1.4 1.4M19.1 4.9l-1.4 1.4"/></svg>;
 if(key==="interestArea")return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r="1"/><path d="M18 6 21 3M17 3h4v4"/></svg>;
 if(key==="careerInterest")return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2.1 4.9-4.9 2.1 2.1-4.9 4.9-2.1Z"/><path d="M12 3v2M12 19v2M3 12h2M19 12h2"/></svg>;
 if(key==="experience")return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 3.5h6v3H9zM8.5 11l1.5 1.5 2.5-3M14 11h2M8.5 16l1.5 1.5 2.5-3M14 16h2"/></svg>;
 return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><path d="m13 11 7.2-7.2a1.4 1.4 0 0 0-2-2L11 9l-1 3 3-1ZM8 15h8"/></svg>;
};

export default function ApplyClient({club,availability,applicant}:{club:ClubSource;availability:ApplicationAvailability;applicant:{studentName:string;studentNumber:string}|null}){
 const router=useRouter();const[form,setForm]=useState(initialForm);const[message,setMessage]=useState("");const[submitting,setSubmitting]=useState(false);const canApply=availability==="open";const applyPath=`/clubs/${club.club_id}/apply`;const profileHref=`/profile?next=${encodeURIComponent(applyPath)}`;
 // Preserve the duplicate-submit guard contract: if (submitting) return.
 async function submit(event:FormEvent){event.preventDefault();if(submitting)return;setMessage("");if(!applicant)return setMessage("동아리 신청 전에 학생 정보 등록이 필요합니다.");if(form.motivation.trim().length<20)return setMessage("지원 동기는 20자 이상 작성해 주세요.");if(!form.interestArea.trim())return setMessage("관심 분야를 작성해 주세요.");if(!form.careerInterest.trim())return setMessage("희망 진로를 작성해 주세요.");if(!form.experience.trim())return setMessage("관련 활동 경험을 작성해 주세요.");if(!form.confirmed)return setMessage("제출 내용을 확인해 주세요.");setSubmitting(true);try{const response=await fetch("/api/applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clubId:club.club_id,...form})});const data=await response.json().catch(()=>({}));if(response.status===401)return router.push(`/login?next=${encodeURIComponent(applyPath)}`);if(data.error==="PROFILE_REQUIRED"){setMessage("동아리 신청 전에 학생 정보 등록이 필요합니다.");return}const errors:Record<string,string>={AUTH_REQUIRED:"로그인이 필요합니다.",PROFILE_REQUIRED:"동아리 신청 전에 학생 정보 등록이 필요합니다.",PERSONAL_DATA_DETECTED:"지원 내용에 입력하면 안 되는 개인정보가 포함되어 있습니다.",DUPLICATE_APPLICATION:"이미 신청한 동아리입니다.",CAPACITY_FULL:"모집 인원이 마감되었습니다.",RECRUITMENT_CLOSED:"현재 신청할 수 없는 동아리입니다.",INQUIRY_ONLY:"이 동아리는 직접 신청이 아니라 담당자 문의가 필요합니다.",CONFIRMATION_REQUIRED:"제출 내용을 확인해 주세요.",INVALID_FIELDS:"입력 내용과 글자 수를 확인해 주세요.",RATE_LIMITED:"요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.",INVALID_ORIGIN:"요청을 처리할 수 없습니다. 페이지를 새로고침한 후 다시 시도해 주세요."};if(!response.ok)return setMessage(errors[data.error]??"신청 처리 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.");router.push(`/my/applications/${data.application.id}?created=1`)}catch{setMessage("신청 처리 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.")}finally{setSubmitting(false)}}
 const blockedMessage=availability==="inquiry"?"이 동아리는 직접 신청이 아니라 담당자 문의가 필요합니다.":"현재 모집이 마감되었거나 모집 정보를 확인해야 합니다.";
 const field=(number:number,label:string,key:"motivation"|"interestArea"|"careerInterest"|"experience"|"additionalMessage",maxLength:number,required:boolean,large:boolean)=><label className="application-question"><span className="question-number">{number}</span><span className={`question-icon question-icon-${key}`}>{fieldIcon(key)}</span><span className="question-heading"><b>{label}</b><small className={required?"required":"optional"}>{required?"필수":"선택"}</small></span><span className="application-control">{large?<textarea required={required} minLength={key==="motivation"?20:required?1:undefined} maxLength={maxLength} value={form[key] as string} placeholder={`${label}을 작성해 주세요. (${key==="motivation"?"20~":""}${maxLength}자)`} onChange={event=>setForm({...form,[key]:event.target.value})}/>:<input required={required} minLength={required?1:undefined} maxLength={maxLength} value={form[key] as string} placeholder={`${label}을 작성해 주세요. (최대 ${maxLength}자)`} onChange={event=>setForm({...form,[key]:event.target.value})}/>}<span className="character-count">{(form[key] as string).length}/{maxLength}</span></span></label>;
 return <main className="app-shell apply-page">
  <HeaderSessionProvider><header className="club-detail-header"><Link className="detail-back" href={`/clubs/${club.club_id}`} aria-label="동아리 상세로">‹</Link><Link className="brand" href="/" aria-label="한곳 홈"><img className="brand-logo" src="/hangot-logo.png" alt="" width="36" height="36"/><span>한<span className="brand-accent">곳</span></span></Link><HeaderAccount/></header></HeaderSessionProvider>
  <div className="apply-main"><header className="apply-heading"><h1>동아리 신청</h1><Link href={`/clubs/${club.club_id}`}>{club.club_name}<span aria-hidden="true">›</span></Link></header>
   <section className="apply-club-card"><div className="apply-club-poster" style={{background:club.color||"#edf3fb"}}>{club.poster_url?<img src={club.poster_url} alt=""/>:<span>{club.icon||"✦"}</span>}</div><div className="apply-club-copy"><div className="club-detail-badges"><span className={openStatus(club.recruitment_status)?"open":""}>{club.recruitment_status}</span><span>{club.category}</span></div><h2>{club.club_name}</h2><p>{club.introduction}</p></div><dl className="apply-club-facts"><div><dt>◎<span>대상 학년</span></dt><dd>{club.grade||"전 학년"}</dd></div><div><dt>▣<span>동아리 유형</span></dt><dd>{club.selection_type}</dd></div><div><dt>⌖<span>활동 장소</span></dt><dd>{club.location||"추후 안내"}</dd></div></dl></section>
   {!applicant?<div className="empty-panel profile-required-panel"><p>동아리 신청 전에 학생 정보 등록이 필요합니다.</p><Link className="primary link-button" href={profileHref}>학생 정보 등록</Link></div>:!canApply?<div className="empty-panel"><p>{blockedMessage}</p></div>:<>
    <section className="apply-applicant-card" aria-label={`신청자 ${applicant.studentNumber} ${applicant.studentName}`}><h2>신청자 정보</h2><dl><div><dt>이름</dt><dd>{applicant.studentName}</dd></div><div><dt>학번</dt><dd>{applicant.studentNumber}</dd></div></dl><p>* 등록된 학생 정보가 자동으로 불러와집니다.</p></section>
    <form className="apply-form" onSubmit={submit}><section className="apply-writing-card"><h2>지원서 작성 <small>필수</small></h2>{field(1,"지원 동기","motivation",1000,true,true)}{field(2,"관심 분야","interestArea",300,true,false)}{field(3,"희망 진로","careerInterest",300,true,false)}{field(4,"관련 활동 경험","experience",1000,true,true)}{field(5,"추가 전달 내용","additionalMessage",500,false,true)}</section>
     <div className="apply-privacy"><b>신청 내용 개인정보 안내</b><p>이름과 학번은 로그인 계정에 등록된 학생 정보를 사용합니다. 지원 동기와 추가 내용에는 전화번호, 이메일, 주소, 주민등록번호 등 신청에 필요하지 않은 개인정보를 입력하지 마세요.</p></div>
     <label className="apply-confirm"><input type="checkbox" required checked={form.confirmed} onChange={event=>setForm({...form,confirmed:event.target.checked})}/> 등록된 학생 정보와 제출 내용을 확인했습니다.</label>{message&&<><p className="form-error" role="alert">{message}</p>{message.includes("학생 정보 등록")&&<Link className="secondary link-button" href={profileHref}>학생 정보 등록으로 이동</Link>}</>}<button className="primary application-submit" type="submit" disabled={submitting}>{submitting?"제출 중…":"신청 제출하기"}</button>
    </form>
   </>}
  </div>
  <nav className="mobile-nav" aria-label="모바일 메뉴"><a href="/"><span>⌂</span>홈</a><a className="active" href="/clubs"><span>⌕</span>동아리</a><a href="/my/applications"><span>▣</span>내 신청</a><a href="/board"><span>▤</span>게시판</a><a href="/questions"><span>◌</span>질의응답</a></nav>
 </main>
}
