"use client";

import Link from "next/link";
import { useState } from "react";
import { HeaderAccount, HeaderNotifications, HeaderSessionProvider } from "../components/HeaderSession";

const links:ReadonlyArray<{section?:string;href:string;label:string;icon:"dashboard"|"clipboard"|"calendar"|"board"|"question"|"user"|"users"}>=[{href:"/admin",label:"대시보드",icon:"dashboard"},{section:"신청 관리",href:"/admin/applications",label:"신청 관리",icon:"clipboard"},{href:"/admin/application-settings",label:"신청 기간 관리",icon:"calendar"},{section:"운영 관리",href:"/admin/board",label:"게시판 관리",icon:"board"},{href:"/admin/questions",label:"Q&A 관리",icon:"question"},{section:"교사 관리",href:"/admin/teachers",label:"교사 관리",icon:"user"},{href:"/admin/teacher-assignments",label:"담당 동아리 배정",icon:"users"}];

function NavigationIcon({name}:{name:string}){const props={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(name==="dashboard")return <svg {...props}><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg>;if(name==="calendar")return <svg {...props}><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16M8 14h3M13 14h3M8 17h3"/></svg>;if(name==="board")return <svg {...props}><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>;if(name==="question")return <svg {...props}><path d="M4 5h16v12H9l-5 4V5Z"/><path d="M9.5 9a2.5 2.5 0 1 1 3.6 2.25c-.75.42-1.1.9-1.1 1.75M12 15h.01"/></svg>;if(name==="users")return <svg {...props}><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3.5 20v-1.5A5.5 5.5 0 0 1 9 13a5.5 5.5 0 0 1 5.5 5.5V20m-5.5-5.5a4.5 4.5 0 0 1 6.5 4V20"/></svg>;if(name==="user")return <svg {...props}><circle cx="12" cy="8" r="3.5"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/></svg>;return <svg {...props}><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4.5V3h6v1.5M9 10h6m-6 4h6m-6 4h4"/></svg>}

export default function AdminShell({activePath,children,wide=false}:{activePath:string;children:React.ReactNode;wide?:boolean}){const[menuOpen,setMenuOpen]=useState(false);return <HeaderSessionProvider><div className={`admin-dashboard-shell${wide?" admin-shell-wide":""}`}><header className="admin-dashboard-header"><Link className="admin-brand" href="/admin"><img src="/hangot-logo.png" width="34" height="34" alt=""/><strong>한곳 <span>관리자</span></strong></Link><button className="admin-mobile-menu" type="button" aria-label="관리자 메뉴 열기" aria-expanded={menuOpen} onClick={()=>setMenuOpen(value=>!value)}><span/><span/><span/></button><div className="admin-header-account"><HeaderNotifications/><HeaderAccount/></div></header><aside className={`admin-dashboard-sidebar${menuOpen?" is-open":""}`} aria-label="관리자 메뉴"><nav>{links.map(item=><div key={item.href}>{item.section&&<p>{item.section}</p>}<Link className={activePath===item.href?"active":""} aria-current={activePath===item.href?"page":undefined} href={item.href} onClick={()=>setMenuOpen(false)}><span><NavigationIcon name={item.icon}/></span>{item.label}</Link></div>)}</nav><div className="admin-sidebar-guide"><span><NavigationIcon name="dashboard"/></span><div><b>관리자 이용 가이드</b><small>사용 방법을 확인하세요.</small></div></div></aside>{children}</div></HeaderSessionProvider>}
