import assert from "node:assert/strict";import{readFile}from"node:fs/promises";import test from"node:test";const root=new URL("../",import.meta.url),read=path=>readFile(new URL(path,root),"utf8");
test("admin application APIs require server-side admin session",async()=>{const sources=await Promise.all([read("app/api/admin/applications/route.ts"),read("app/api/admin/applications/[id]/route.ts"),read("app/api/admin/applications/[id]/status/route.ts")]);for(const source of sources){assert.match(source,/requireUser\(\["admin"\]\)/);assert.doesNotMatch(source,/authUserId|recoveryHash|email|token/i)}});
test("admin list keeps filters, pagination, and allowlisted applicant profile",async()=>{const source=await read("app/api/admin/applications/route.ts");for(const field of["page","pageSize","status","clubId","search","sort"])assert.match(source,new RegExp(`params\\.get\\("${field}"\\)`));assert.match(source,/Math\.min\(100/);for(const field of["applicationNumber","studentName","studentNumber","userAlias","clubName","submittedAt"])assert.match(source,new RegExp(`${field}:`));assert.doesNotMatch(source,/auth_user_id|recovery_hash|privacy_consent_at|email|serviceKey/i)});
test("admin detail exposes only application profile fields",async()=>{const source=await read("app/api/admin/applications/[id]/route.ts");for(const field of["studentName","studentNumber","userAlias"])assert.match(source,new RegExp(`${field}:`));assert.doesNotMatch(source,/auth_user_id|recovery_hash|privacy_consent_at|email|serviceKey/i)});
test("admin search resolves name, student number, and alias to safe user ids",async()=>{const[route,users,repo]=await Promise.all([read("app/api/admin/applications/route.ts"),read("app/lib/database/users.ts"),read("app/lib/database/applications.ts")]);assert.match(route,/findApplicationUserIds\(search\)/);assert.match(route,/searchUserIds/);for(const field of["alias","student_name","student_number"])assert.match(users,new RegExp(`${field}\\.ilike`));assert.match(users,/\^usr_\[a-zA-Z0-9\]\+\$/);assert.match(repo,/application_number\.ilike/);assert.match(repo,/motivation\.ilike/);assert.match(repo,/user_id\.in/);assert.match(repo,/sanitizeApplicationSearch/);assert.match(repo,/\[\^\\p\{L\}\\p\{N\}\\s-\]/u);assert.match(repo,/countApplications[\s\S]*searchFilter/)});
test("admin filters reset and applicant fields remain distinct",async()=>{const source=await read("app/admin/applications/AdminApplicationsClient.tsx");assert.match(source,/학번, 이름, 신청 번호 또는 지원 동기/);assert.match(source,/const initialFilters=\{status:"",clubId:"",search:"",sort:"newest"\}/);assert.match(source,/setFilters\(initialFilters\)/);assert.match(source,/setApplied\(initialFilters\)/);assert.match(source,/setPage\(1\)/);assert.match(source,/신청번호/);assert.match(source,/item\.userAlias/);assert.match(source,/item\.clubName/)});
test("admin pages and APIs reject non-admin roles on the server",async()=>{const[security,layout,list,detail]=await Promise.all([read("app/lib/security.ts"),read("app/admin/layout.tsx"),read("app/api/admin/applications/route.ts"),read("app/api/admin/applications/[id]/route.ts")]);assert.match(security,/FORBIDDEN/);assert.match(security,/status: 403/);assert.match(layout,/requirePageRole\(\["admin"\]/);for(const source of[list,detail])assert.match(source,/requireUser\(\["admin"\]\)/)});
test("review transitions use atomic RPC with optimistic conflict and audit",async()=>{const[route,repo,sql]=await Promise.all([read("app/api/admin/applications/[id]/status/route.ts"),read("app/lib/database/applications.ts"),read("supabase/migrations/202608070002_harden_application_audit.sql")]);assert.match(route,/body\.reviewComment\.length\s*>\s*1000/);assert.match(route,/actorUserId:\s*auth\.user\.id/);assert.match(route,/APPLICATION_CONFLICT/);assert.match(repo,/rpc\/review_application/);assert.match(sql,/v_current\.status <> p_expected_status/);assert.match(sql,/insert into public\.audit_logs/)});
test("student detail exposes review result without identity fields",async()=>{const source=await read("app/api/applications/[id]/route.ts");assert.match(source,/reviewedAt:row\.reviewed_at/);assert.match(source,/reviewComment:row\.review_comment/);assert.doesNotMatch(source,/studentName|studentNumber|authUserId|googleId|email/i)});
