import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { isSchoolGoogleEmail,normalizeGoogleEmail,validApprovalEmail } from "../app/lib/login-policy.ts";

const root=new URL("../",import.meta.url),read=path=>readFile(new URL(path,root),"utf8");

test("school-domain policy normalizes email and only matches the exact configured domain",()=>{assert.equal(normalizeGoogleEmail(" Teacher@School.Example "),"teacher@school.example");assert.equal(isSchoolGoogleEmail("student@school.example","SCHOOL.EXAMPLE"),true);assert.equal(isSchoolGoogleEmail("student@sub.school.example","school.example"),false);assert.equal(isSchoolGoogleEmail("student@external.example","school.example"),false);assert.equal(validApprovalEmail("teacher@external.example"),true);assert.equal(validApprovalEmail("not-an-email"),false)});

test("callback checks existing DB users before enrollment policy and blocks inactive accounts",async()=>{const callback=await read("app/auth/callback/route.ts");assert.ok(callback.indexOf("findUserByAuthId(data.user.id)")<callback.indexOf("user=await ensureGoogleAppUser"));assert.match(callback,/existing&&!existing\.isActive/);assert.match(callback,/account-inactive/);assert.match(callback,/clearProviderSession/);assert.match(callback,/authRequest\("\/logout"/)});

test("existing external privileged roles survive while external students do not bypass policy",async()=>{const callback=await read("app/auth/callback/route.ts");assert.match(callback,/existing\.role==="student"&&!schoolAccount/);assert.match(callback,/external-account-not-approved/);assert.doesNotMatch(callback,/existing\.role==="club_manager".*reject|existing\.role==="admin".*reject/)});

test("new school users are server-forced students and external users require a DB claim",async()=>{const[callback,security,users]=await Promise.all([read("app/auth/callback/route.ts"),read("app/lib/security.ts"),read("app/lib/database/users.ts")]);assert.match(callback,/schoolAccount\).*ensureGoogleAppUser/);assert.match(callback,/claimApprovedGoogleAppUser/);assert.match(users,/role:"student"/);assert.doesNotMatch(callback,/body\.(?:role|reservedRole)|searchParams.*role/);assert.doesNotMatch(security,/reservedRole/)});

test("allowed account claim assigns only the reserved DB role and is single-use",async()=>{const sql=await read("supabase/migrations/202608310002_allowed_accounts.sql");assert.match(sql,/reserved_role in \('club_manager', 'admin'\)/);assert.match(sql,/v_approval\.reserved_role/);assert.match(sql,/is_active[\s\S]*used_at is null[\s\S]*expires_at is null or expires_at > p_now/);assert.match(sql,/for update/);assert.match(sql,/set used_at = p_now, linked_user_id = v_user\.id/);assert.doesNotMatch(sql,/reserved_role in \([^)]*student/)});

test("allowed accounts are private, unique while active, and preserve used records",async()=>{const[sql,repo]=await Promise.all([read("supabase/migrations/202608310002_allowed_accounts.sql"),read("app/lib/database/allowed-accounts.ts")]);assert.match(sql,/unique index[\s\S]*normalized_email[\s\S]*where is_active/);assert.match(sql,/enable row level security/);assert.match(sql,/revoke all on public\.allowed_accounts from public, anon, authenticated/);assert.match(sql,/grant all on public\.allowed_accounts to service_role/);assert.match(repo,/used_at:"is\.null"/);assert.doesNotMatch(repo,/method:"DELETE"/)});

test("admin approval APIs enforce admin, origin, size, rate, and role allowlists",async()=>{const sources=await Promise.all([read("app/api/admin/allowed-accounts/route.ts"),read("app/api/admin/allowed-accounts/[id]/route.ts")]);for(const source of sources){assert.match(source,/requireUser\(\["admin"\]\)/);assert.match(source,/sameOrigin\(request\)/);assert.match(source,/hasOversizedBody/);assert.match(source,/checkRateLimit/)}assert.match(sources[0],/new Set\(\["club_manager","admin"\]\)/);assert.match(sources[0],/validApprovalEmail/);assert.doesNotMatch(sources[0],/actor.*email|after_data:\{[^}]*email/)});

test("admin UI is the only UI that lists approval email and supports unused cancellation",async()=>{const client=await read("app/admin/teachers/TeachersClient.tsx");assert.match(client,/\/api\/admin\/allowed-accounts/);assert.match(client,/Google 계정 이메일/);assert.match(client,/담당교사/);assert.match(client,/관리자/);assert.match(client,/account\.isActive&&!account\.usedAt/);assert.match(client,/승인 취소/)});

test("club manager demotion deletes assignments and audits the removal in one transaction",async()=>{const[sql,route]=await Promise.all([read("supabase/migrations/202608310002_allowed_accounts.sql"),read("app/api/admin/users/[id]/role/route.ts")]);assert.match(sql,/function public\.demote_club_manager/);assert.match(sql,/delete from public\.teacher_clubs where teacher_user_id = p_target_user_id/);assert.match(sql,/get diagnostics v_removed_count = row_count/);assert.match(sql,/assignmentCountRemoved/);assert.match(sql,/insert into public\.audit_logs/);assert.match(route,/demoteClubManager/);assert.match(route,/assignmentCountRemoved/)});

test("session lookup never auto-creates a user outside the callback policy",async()=>{const security=await read("app/lib/security.ts"),current=security.slice(security.indexOf("export async function currentUser"),security.indexOf("export async function ensureGoogleAppUser"));assert.match(current,/findUserByAuthId/);assert.doesNotMatch(current,/ensureGoogleAppUser|ensureUser/)});

test("login presents distinct approval and inactive account messages",async()=>{const login=await read("app/login/page.tsx");assert.match(login,/external-account-not-approved/);assert.match(login,/한곳 사용 승인을 받지 않았습니다/);assert.match(login,/account-inactive/);assert.match(login,/비활성화된 계정/)});

test("teacher APIs retain role and assigned-club scope checks",async()=>{const sources=await Promise.all([read("app/api/teacher/applications/route.ts"),read("app/api/teacher/applications/[id]/route.ts"),read("app/api/teacher/applications/[id]/status/route.ts"),read("app/api/questions/[id]/answer/route.ts")]);for(const source of sources.slice(0,3)){assert.match(source,/requireUser\(\["club_manager"\]\)/);assert.match(source,/teacherClubIds\(auth\.user\.id\)/)}assert.match(sources[3],/auth\.user\.role === "club_manager"[\s\S]*teacherClubIds/)});
