import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("../",import.meta.url);const read=p=>readFile(new URL(p,root),"utf8");
test("removes anonymous endpoints and login UI",async()=>{await assert.rejects(access(new URL("app/api/auth/anonymous/route.ts",root)));await assert.rejects(access(new URL("app/api/auth/recover/route.ts",root)));const login=await read("app/login/page.tsx");assert.match(login,/Google 계정으로 로그인/);assert.doesNotMatch(login,/익명|복구 코드/)});
test("uses Google PKCE callback and safe internal return paths",async()=>{const[start,callback,auth]=await Promise.all([read("app/api/auth/google/route.ts"),read("app/auth/callback/route.ts"),read("app/lib/supabase-auth.ts")]);assert.match(start,/provider", "google"/);assert.match(start,/code_challenge_method", "s256"/);assert.match(callback,/grant_type=pkce/);assert.match(auth,/safeInternalPath/)});
test("keeps OAuth cookies and callbacks on the configured production origin",async()=>{const[start,callback]=await Promise.all([read("app/api/auth/google/route.ts"),read("app/auth/callback/route.ts")]);assert.match(start,/new URL\(process\.env\.APP_URL \|\| url\.origin\)\.origin/);assert.match(start,/url\.origin !== appOrigin/);assert.match(start,/new URL\("\/api\/auth\/google", appOrigin\)/);assert.match(start,/`\$\{appOrigin\}\/auth\/callback`/);assert.match(callback,/new URL\(process\.env\.APP_URL \|\| url\.origin\)\.origin/);assert.match(callback,/verifierCookie: Boolean\(flow\.verifier\)/);assert.match(callback,/authCode: Boolean\(code\)/);assert.doesNotMatch(callback,/verifierCookie: flow\.verifier|authCode: code[,\n]/);assert.match(callback,/new URL\(flow\.next, appOrigin\)/)});
test("classifies OAuth startup failures without logging secret values",async()=>{const[start,login]=await Promise.all([read("app/api/auth/google/route.ts"),read("app/login/page.tsx")]);for(const code of ["not-configured","oauth-cookie","oauth-pkce","oauth-start"]){assert.match(start,new RegExp(code));assert.match(login,new RegExp(`"${code}"`))}assert.match(start,/name: error\.name/);assert.match(start,/message: error\.message/);assert.match(start,/stack: error\.stack/);for(const key of ["NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_ANON_KEY","APP_URL","NODE_ENV"]){assert.match(start,new RegExp(`${key}: Boolean\\(process\\.env\\.${key}\\)`))}assert.doesNotMatch(start,/SUPABASE_SERVICE_ROLE_KEY|access_token|refresh_token|CLIENT_SECRET/)});
test("forces new users to student and keeps secrets out of the login UI",async()=>{const users=await read("app/lib/database/users.ts");assert.match(users,/role:"student"/);const login=await read("app/login/page.tsx");assert.doesNotMatch(login,/SERVICE_ROLE|CLIENT_SECRET|access_token|refresh_token|process\.env/)});
