import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("snapshot sync is admin-only, same-origin, bodyless, bounded, and rate limited",async()=>{const route=await read("app/api/admin/sync/route.ts");assert.match(route,/requireUser\(\["admin"\]\)/);assert.match(route,/sameOrigin\(request\)/);assert.match(route,/hasOversizedBody\(request,1_024\)/);assert.match(route,/BODY_NOT_ALLOWED/);assert.match(route,/admin-google-sheets-sync/);assert.match(route,/limit:3/)});
test("snapshot comes from current applications rather than stale application jobs",async()=>{const[route,db]=await Promise.all([read("app/api/admin/sync/route.ts"),read("app/lib/database/applications.ts")]);assert.match(route,/listApplicationSheetSnapshot\(\)/);assert.match(db,/applications\?/);assert.match(db,/submitted_at\.asc,id\.asc/);assert.doesNotMatch(route,/listSyncJobs\(\["pending","failed"\],"application"\)/)});
test("snapshot columns exclude student identity and application answers",async()=>{const route=await read("app/api/admin/sync/route.ts"),block=route.slice(route.indexOf('const rows='),route.indexOf("await replaceApplicationSheet"));for(const field of["application_id","application_number","club_id","club_name","status","submitted_at","updated_at","reviewed_at","cancelled_at","synced_at"])assert.match(block,new RegExp(field));for(const forbidden of["student_name","student_number","email","user_id","alias","motivation","interest_area","career_interest","experience","additional_answer","review_comment"])assert.doesNotMatch(block,new RegExp(forbidden))});
test("snapshot ordering and duplicate removal are deterministic",async()=>{const route=await read("app/api/admin/sync/route.ts");assert.match(route,/submitted_at\.localeCompare/);assert.match(route,/a\.id\.localeCompare/);assert.match(route,/new Set<string>/);assert.match(route,/seen\.has\(row\.id\)/)});
test("sheet replacement writes first and clears only stale trailing rows",async()=>{const sheets=await read("app/lib/sheets.ts");assert.match(sheets,/export async function replaceApplicationSheet/);assert.ok(sheets.indexOf('method:"PUT"')<sheets.indexOf(":clear"));assert.match(sheets,/valueInputOption=RAW/);assert.match(sheets,/oldCount>safeRows\.length/)});
test("formula injection defense handles leading whitespace and control characters",async()=>{const security=await read("app/lib/security.ts");assert.match(security,/\[\\u0000-\\u0020\]\*\[=\+\\-@\]/);assert.match(security,/`'\$\{value\}`/)});
test("server credentials are required and never returned to the client",async()=>{const[sheets,route]=await Promise.all([read("app/lib/sheets.ts"),read("app/api/admin/sync/route.ts")]);for(const name of["GOOGLE_SERVICE_ACCOUNT_EMAIL","GOOGLE_PRIVATE_KEY","GOOGLE_SHEETS_SPREADSHEET_ID","GOOGLE_SHEETS_APPLICATION_SHEET"])assert.match(sheets,new RegExp(name));assert.match(sheets,/SHEETS_NOT_CONFIGURED/);assert.doesNotMatch(route,/spreadsheetId|privateKey|access_token|GOOGLE_PRIVATE_KEY/)});
test("sync errors are safe codes and application rows remain untouched",async()=>{const route=await read("app/api/admin/sync/route.ts");for(const code of["SHEETS_NOT_CONFIGURED","SHEETS_PERMISSION_DENIED","SYNC_IN_PROGRESS","SYNC_FAILED"])assert.match(route,new RegExp(code));assert.doesNotMatch(route,/createApplication|cancelApplication|reviewApplication|updateApplication/)});
test("sync audit contains counts and state but no student data",async()=>{const route=await read("app/api/admin/sync/route.ts");assert.match(route,/google_sheets\.sync_completed/);assert.match(route,/google_sheets\.sync_failed/);assert.match(route,/processedCount/);for(const forbidden of["studentName","studentNumber","motivation","reviewComment","privateKey","accessToken"])assert.doesNotMatch(route,new RegExp(forbidden))});
test("application create and cancel no longer depend on Sheets jobs",async()=>{const[create,cancel]=await Promise.all([read("app/api/applications/route.ts"),read("app/api/applications/[id]/cancel/route.ts")]);assert.doesNotMatch(create,/upsertSyncJob|Google|Sheet/);assert.doesNotMatch(cancel,/upsertSyncJob|Google|Sheet/);assert.match(create,/createApplication/);assert.match(cancel,/cancelApplication/)});
test("review state changes stay isolated from Sheets",async()=>{for(const path of["app/api/admin/applications/[id]/status/route.ts","app/api/teacher/applications/[id]/status/route.ts"]){const route=await read(path);assert.match(route,/reviewApplication/);assert.doesNotMatch(route,/Google|Sheet|syncJob/)}});
test("legacy sync job responses omit payload while question sync remains separate",async()=>{const route=await read("app/api/admin/sync/route.ts"),getBlock=route.slice(route.indexOf("export async function GET"),route.indexOf("export async function POST"));assert.doesNotMatch(getBlock,/payload/);assert.match(route,/listSyncJobs\(\["pending","failed"\],"question"\)/);assert.match(route,/upsertSheetRow/)});
test("UI disables duplicate clicks and shows count and safe configuration errors",async()=>{const ui=await read("app/admin/AdminClient.tsx");assert.match(ui,/if\(syncing\)return/);assert.match(ui,/disabled=\{syncing\}/);assert.match(ui,/aria-busy=\{syncing\}/);assert.match(ui,/result\.processed/);assert.match(ui,/Google Sheets 연동이 설정되지 않았습니다/)});
test("environment examples contain names only and local secrets remain ignored",async()=>{const[env,local,ignore]=await Promise.all([read(".env.example"),read(".env.local.example"),read(".gitignore")]);for(const name of["GOOGLE_SERVICE_ACCOUNT_EMAIL","GOOGLE_PRIVATE_KEY","GOOGLE_SHEETS_SPREADSHEET_ID","GOOGLE_SHEETS_APPLICATION_SHEET","GOOGLE_SHEETS_QUESTION_SHEET"]){assert.match(env,new RegExp(`^${name}=$`,"m"));assert.match(local,new RegExp(`^${name}=$`,"m"))}assert.match(ignore,/\.env\*/);assert.match(ignore,/!\.env\.example/)});
test("snapshot sync uses an in-runtime lock and documents its multi-instance limit",async()=>{const route=await read("app/api/admin/sync/route.ts");assert.match(route,/__hangotSheetsSyncRunning/);assert.match(route,/multiple production instances/);assert.match(route,/finally\{runtime\.__hangotSheetsSyncRunning=false\}/)});
test("A1 ranges safely encode Korean, spaces, and apostrophes for every values operation",async()=>{const sheets=await read("app/lib/sheets.ts"),encode=(sheet,cells)=>encodeURIComponent(`'${sheet.replaceAll("'","''")}'!${cells}`).replace(/[!'()*]/g,char=>`%${char.charCodeAt(0).toString(16).toUpperCase()}`);assert.equal(decodeURIComponent(encode("신청","A:A")),"'신청'!A:A");assert.equal(decodeURIComponent(encode("신청 현황","A1:J20")),"'신청 현황'!A1:J20");assert.equal(decodeURIComponent(encode("교사's 신청","A2:J9")),"'교사''s 신청'!A2:J9");assert.match(sheets,/sheetValuesRange\(sheetName,"A:A"\)/);assert.match(sheets,/sheetValuesRange\(sheetName,target\)/);assert.match(sheets,/sheetValuesRange\(applicationSheet,`A1:J/);assert.match(sheets,/sheetValuesRange\(applicationSheet,`A\$\{safeRows\.length\+1\}:J\$\{oldCount\}`\)/);assert.match(encode("신청","A:A"),/^%27.+%27%21A%3AA$/)});
