import "server-only";
import { databaseRequest, isUniqueViolation, query } from "./client";

export type ApplicationStatus="submitted"|"under_review"|"waiting"|"approved"|"rejected"|"cancelled";
export type ApplicationRow={id:string;application_number:string;user_id:string;club_id:string;status:ApplicationStatus;motivation:string;interest_area:string|null;career_interest:string;experience:string;additional_answer:string|null;submitted_at:string;cancelled_at:string|null;reviewed_at:string|null;reviewed_by:string|null;review_comment:string|null;google_sheet_synced:boolean;google_sheet_synced_at:string|null;updated_at:string;users?:{alias:string;student_name:string|null;student_number:string|null}|null;clubs?:{name:string}|null};
const select="*,users!applications_user_id_fkey(alias,student_name,student_number),clubs(name)";
export async function findApplication(id:string,userId?:string){const rows=await databaseRequest<ApplicationRow[]>(`applications?${query({select,id:`eq.${id}`,user_id:userId?`eq.${userId}`:undefined,limit:1})}`);return rows[0]??null}
export async function findDuplicateApplication(userId:string,clubId:string){const rows=await databaseRequest<ApplicationRow[]>(`applications?${query({select:"id",user_id:`eq.${userId}`,club_id:`eq.${clubId}`,limit:1})}`);return rows[0]??null}
export async function countActiveClubApplications(clubId:string){const rows=await databaseRequest<Array<{id:string}>>(`applications?${query({select:"id",club_id:`eq.${clubId}`,status:"neq.cancelled"})}`);return rows.length}
export async function createApplication(row:Record<string,unknown>){try{return await databaseRequest<ApplicationRow[]>("applications",{method:"POST",headers:{prefer:"return=representation"},body:JSON.stringify(row)})}catch(e){if(isUniqueViolation(e))throw new Error("DUPLICATE_APPLICATION");throw e}}
export async function listOwnApplications(userId:string){return databaseRequest<ApplicationRow[]>(`applications?${query({select:"*",user_id:`eq.${userId}`,order:"submitted_at.desc"})}`)}
export async function cancelApplication(id:string,userId:string,expected:ApplicationStatus[]){return databaseRequest<ApplicationRow[]>(`applications?${query({id:`eq.${id}`,user_id:`eq.${userId}`,status:`in.(${expected.join(",")})`,select:"*"})}`,{method:"PATCH",headers:{prefer:"return=representation"},body:JSON.stringify({status:"cancelled",cancelled_at:new Date().toISOString(),updated_at:new Date().toISOString(),google_sheet_synced:false})})}
type ApplicationSearchOptions={status?:string;clubId?:string;search?:string;searchUserIds?:string[];clubIds?:string[];startDate?:string;endDate?:string};
function searchFilter(search?:string,userIds:string[]=[]){if(!search)return undefined;const conditions=[`application_number.ilike.*${search}*`,`motivation.ilike.*${search}*`];if(userIds.length)conditions.push(`user_id.in.(${userIds.join(",")})`);return `(${conditions.join(",")})`}
export function sanitizeApplicationSearch(value:string){return value.replace(/[^\p{L}\p{N}\s-]/gu,"").replace(/\s+/g," ").trim().slice(0,200)}
export async function listApplications(options:ApplicationSearchOptions&{page:number;pageSize:number;sort:"oldest"|"newest"}){const filters:Record<string,string|number|undefined>={select,order:`submitted_at.${options.sort==="oldest"?"asc":"desc"}`,limit:options.pageSize,offset:(options.page-1)*options.pageSize,status:options.status?`eq.${options.status}`:undefined,club_id:options.clubId?`eq.${options.clubId}`:options.clubIds?`in.(${options.clubIds.join(",")})`:undefined,submitted_at:options.startDate?`gte.${options.startDate}`:undefined,and:options.endDate?`(submitted_at.lte.${options.endDate})`:undefined,or:searchFilter(options.search,options.searchUserIds)};return databaseRequest<ApplicationRow[]>(`applications?${query(filters)}`)}
export async function listActionableApplications(limit=5){return databaseRequest<ApplicationRow[]>(`applications?${query({select,order:"submitted_at.desc",limit,status:"in.(submitted,under_review,waiting)"})}`)}
export async function countApplications(options:ApplicationSearchOptions){const rows=await databaseRequest<Array<{id:string}>>(`applications?${query({select:"id",status:options.status?`eq.${options.status}`:undefined,club_id:options.clubId?`eq.${options.clubId}`:options.clubIds?`in.(${options.clubIds.join(",")})`:undefined,submitted_at:options.startDate?`gte.${options.startDate}`:undefined,and:options.endDate?`(submitted_at.lte.${options.endDate})`:undefined,or:searchFilter(options.search,options.searchUserIds)})}`);return rows.length}
export async function applicationStatusCounts(){const rows=await databaseRequest<Array<{status:ApplicationStatus}>>("applications?select=status");return rows.reduce<Record<string,number>>((a,r)=>(a[r.status]=(a[r.status]??0)+1,a),{})}
export type ApplicationSheetRow=Pick<ApplicationRow,"id"|"application_number"|"club_id"|"status"|"submitted_at"|"updated_at"|"reviewed_at"|"cancelled_at">&{clubs?:{name:string}|null};
export async function listApplicationSheetSnapshot(){
 const rows:ApplicationSheetRow[]=[],pageSize=1000;
 for(let offset=0;;offset+=pageSize){
  const page=await databaseRequest<ApplicationSheetRow[]>(`applications?${query({select:"id,application_number,club_id,status,submitted_at,updated_at,reviewed_at,cancelled_at,clubs(name)",order:"submitted_at.asc,id.asc",limit:pageSize,offset})}`);
  rows.push(...page);if(page.length<pageSize)return rows;
 }
}
export async function reviewApplication(input:{applicationId:string;expectedStatus:string;nextStatus:string;reviewComment:string|null;actorUserId:string;actorRole:"admin"|"teacher"}){return databaseRequest<ApplicationRow[]>("rpc/review_application",{method:"POST",body:JSON.stringify({p_application_id:input.applicationId,p_expected_status:input.expectedStatus,p_next_status:input.nextStatus,p_review_comment:input.reviewComment,p_actor_user_id:input.actorUserId,p_actor_role:input.actorRole})})}
