"use client";

import { FormEvent,useCallback,useEffect,useRef,useState } from "react";
import AdminShell from "../AdminShell";

type Post={id:string;author:"익명";category:string;clubId:string|null;title:string;content:string;isNotice:boolean;isHidden:boolean;createdAt:string;updatedAt:string};
type Payload={posts:Post[];categories:string[];pagination:{page:number;pageSize:number;total:number;totalPages:number};summary:{total:number}};
type Filters={search:string;category:string;status:string;notice:string};
const initialFilters:Filters={search:"",category:"",status:"",notice:""};
const formatDate=(value:string)=>new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));

export default function AdminBoardClient(){
 const[data,setData]=useState<Payload|null>(null),[filters,setFilters]=useState(initialFilters),[applied,setApplied]=useState(initialFilters),[page,setPage]=useState(1),[error,setError]=useState("");
 const[selected,setSelected]=useState<Post|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),drawerRef=useRef<HTMLElement>(null),returnFocusRef=useRef<HTMLElement|null>(null);
 const load=useCallback(async()=>{const params=new URLSearchParams({...applied,page:String(page),pageSize:"20"}),response=await fetch(`/api/admin/posts?${params}`,{cache:"no-store"});if(!response.ok){setError(response.status===403?"관리자 권한이 없습니다.":"게시글 목록을 불러오지 못했습니다.");return}setError("");setData(await response.json())},[applied,page]);
 useEffect(()=>{void load()},[load]);
 const close=useCallback(()=>{setSelected(null);setMessage("");setTimeout(()=>returnFocusRef.current?.focus(),0)},[]);
 useEffect(()=>{if(!selected)return;drawerRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close()};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[selected,close]);
 function submit(event:FormEvent){event.preventDefault();setApplied(filters);setPage(1)}
 function reset(){setFilters(initialFilters);setApplied(initialFilters);setPage(1)}
 function open(post:Post,event:React.MouseEvent<HTMLElement>){returnFocusRef.current=event.currentTarget;setSelected(post);setMessage("")}
 async function update(change:Pick<Partial<Post>,"isHidden"|"isNotice">){if(!selected)return;if(change.isHidden===true&&!window.confirm("이 게시글을 학생 게시판에서 숨기시겠습니까?"))return;setSaving(true);setMessage("");try{const response=await fetch(`/api/admin/posts/${selected.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(change)}),result=await response.json().catch(()=>({}));if(!response.ok){setMessage("상태를 변경하지 못했습니다.");return}setSelected(result.post);setMessage("게시글 상태를 변경했습니다.");await load()}finally{setSaving(false)}}
 const pages=data?Array.from({length:Math.min(5,data.pagination.totalPages)},(_,index)=>Math.max(1,Math.min(data.pagination.totalPages-4,page-2))+index).filter(value=>value<=data.pagination.totalPages):[];
 const hasFilters=Object.values(applied).some(Boolean);
 return <AdminShell activePath="/admin/board" wide><main className="admin-dashboard-main admin-board-workspace"><div className="admin-dashboard-title"><h1>게시판 관리</h1><p>학생 게시판의 글을 확인하고 공지·숨김 상태를 관리할 수 있습니다.</p></div>
  <form className="admin-board-filter-panel" onSubmit={submit}><label><span>검색</span><input maxLength={120} placeholder="제목, 본문, 카테고리 검색" value={filters.search} onChange={event=>setFilters({...filters,search:event.target.value})}/></label><label><span>카테고리</span><select value={filters.category} onChange={event=>setFilters({...filters,category:event.target.value})}><option value="">전체</option>{data?.categories.map(category=><option key={category} value={category}>{category}</option>)}</select></label><label><span>상태</span><select value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})}><option value="">전체</option><option value="public">공개</option><option value="hidden">숨김</option></select></label><label><span>공지</span><select value={filters.notice} onChange={event=>setFilters({...filters,notice:event.target.value})}><option value="">전체</option><option value="notice">공지</option><option value="regular">일반글</option></select></label><div className="admin-filter-buttons"><button type="button" onClick={reset}>초기화</button><button type="submit">검색</button></div></form>
  <section className="admin-board-list-panel"><header><strong>총 {data?.pagination.total??0}건</strong></header>{error?<div className="admin-dashboard-empty">{error}</div>:!data?<div className="admin-dashboard-empty">게시글 목록을 불러오는 중입니다.</div>:data.posts.length===0?<div className="admin-dashboard-empty">{!hasFilters&&data.summary.total===0?"등록된 게시글이 없습니다.":"조건에 맞는 게시글이 없습니다."}</div>:<div className="admin-board-table" role="table" aria-label="게시글 목록"><div className="admin-board-table-head" role="row"><span>카테고리</span><span>제목</span><span>작성자</span><span>공지</span><span>상태</span><span>작성일</span><span>관리</span></div>{data.posts.map(post=><article className="admin-board-table-row" role="row" key={post.id}><span data-label="카테고리">{post.category}</span><strong data-label="제목">{post.title}</strong><span data-label="작성자">익명</span><span data-label="공지"><b className={`admin-board-badge ${post.isNotice?"is-notice":"is-regular"}`}>{post.isNotice?"공지":"일반글"}</b></span><span data-label="상태"><b className={`admin-board-badge ${post.isHidden?"is-hidden":"is-public"}`}>{post.isHidden?"숨김":"공개"}</b></span><time data-label="작성일" dateTime={post.createdAt}>{formatDate(post.createdAt)}</time><button type="button" onClick={event=>open(post,event)}>상세 보기 <b aria-hidden="true">›</b></button></article>)}</div>}
   {data&&data.pagination.totalPages>1&&<nav className="admin-list-pagination" aria-label="게시글 목록 페이지"><button type="button" disabled={page<=1} onClick={()=>setPage(page-1)} aria-label="이전 페이지">‹</button>{pages.map(number=><button type="button" className={number===page?"active":""} aria-current={number===page?"page":undefined} key={number} onClick={()=>setPage(number)}>{number}</button>)}<button type="button" disabled={page>=data.pagination.totalPages} onClick={()=>setPage(page+1)} aria-label="다음 페이지">›</button></nav>}
  </section>
  {selected&&<><button className="admin-drawer-backdrop" type="button" aria-label="게시글 상세 닫기" onClick={close}/><aside className="admin-board-drawer" ref={drawerRef} tabIndex={-1} aria-label="게시글 상세 정보"><header><h2>게시글 상세 정보</h2><button type="button" aria-label="게시글 상세 닫기" onClick={close}>×</button></header><section className="admin-board-detail"><div className="admin-board-detail-meta"><span>{selected.category}</span>{selected.isNotice&&<b className="admin-board-badge is-notice">공지</b>}<b className={`admin-board-badge ${selected.isHidden?"is-hidden":"is-public"}`}>{selected.isHidden?"숨김":"공개"}</b></div><time dateTime={selected.createdAt}>{formatDate(selected.createdAt)}</time><h3>{selected.title}</h3><p>{selected.content}</p><dl><div><dt>작성자</dt><dd>익명</dd></div><div><dt>현재 상태</dt><dd>{selected.isHidden?"숨김":"공개"}</dd></div></dl></section><section className="admin-board-moderation"><h3>운영 관리</h3>{message&&<p role="status" className="form-success">{message}</p>}<div><button type="button" disabled={saving} onClick={()=>update({isNotice:!selected.isNotice})}>{selected.isNotice?"공지 해제":"공지로 지정"}</button><button className={selected.isHidden?"restore":"hide"} type="button" disabled={saving} onClick={()=>update({isHidden:!selected.isHidden})}>{selected.isHidden?"다시 공개":"숨기기"}</button></div></section></aside></>}
 </main></AdminShell>
}
