"use client";

import { FormEvent,useCallback,useEffect,useRef,useState } from "react";
import AdminShell from "../AdminShell";

type Question={id:string;clubId:string;clubName:string;author:"익명";title:string;content:string;isPrivate:boolean;isDeleted:boolean;status:"waiting"|"answered"|"closed";createdAt:string;updatedAt:string};
type Detail=Question&{answer:{content:string;role:string;createdAt:string}|null};
type Club={club_id:string;club_name:string};
type Payload={questions:Question[];pagination:{page:number;pageSize:number;total:number;totalPages:number};summary:{total:number;statusCounts:Record<string,number>;privateCount:number;deletedCount:number}};
type Filters={search:string;clubId:string;status:string;privacy:string;period:string;deleted:string};
const initialFilters:Filters={search:"",clubId:"",status:"",privacy:"",period:"",deleted:""};
const statusLabels:Record<string,string>={waiting:"미답변",answered:"답변완료",closed:"종료"};
const formatDate=(value:string)=>new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));

export default function AdminQuestionsClient(){
 const[data,setData]=useState<Payload|null>(null),[clubs,setClubs]=useState<Club[]>([]),[filters,setFilters]=useState(initialFilters),[applied,setApplied]=useState(initialFilters),[page,setPage]=useState(1),[error,setError]=useState("");
 const[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null),[detailError,setDetailError]=useState(""),[answer,setAnswer]=useState(""),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),drawerRef=useRef<HTMLElement>(null),returnFocusRef=useRef<HTMLElement|null>(null);
 const load=useCallback(async()=>{const params=new URLSearchParams({...applied,page:String(page),pageSize:"20"}),response=await fetch(`/api/admin/questions?${params}`,{cache:"no-store"});if(!response.ok){setError(response.status===403?"관리자 권한이 없습니다.":"질문 목록을 불러오지 못했습니다.");return}setError("");setData(await response.json())},[applied,page]);
 const loadDetail=useCallback(async(id:string)=>{setDetail(null);setDetailError("");const response=await fetch(`/api/admin/questions/${id}`,{cache:"no-store"});if(!response.ok){setDetailError("질문 상세를 불러오지 못했습니다.");return}setDetail((await response.json()).question)},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{fetch("/api/clubs").then(response=>response.json()).then(result=>setClubs(result.clubs??[])).catch(()=>{})},[]);
 const close=useCallback(()=>{setSelectedId(null);setDetail(null);setAnswer("");setMessage("");setTimeout(()=>returnFocusRef.current?.focus(),0)},[]);
 useEffect(()=>{if(!selectedId)return;void loadDetail(selectedId);drawerRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close()};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[selectedId,loadDetail,close]);
 function submit(event:FormEvent){event.preventDefault();setApplied(filters);setPage(1)}
 function reset(){setFilters(initialFilters);setApplied(initialFilters);setPage(1)}
 function quick(type:"all"|"waiting"|"answered"|"private"|"deleted"){const next={...filters,status:type==="waiting"||type==="answered"?type:"",privacy:type==="private"?"private":"",deleted:type==="deleted"?"deleted":""};setFilters(next);setApplied(next);setPage(1)}
 function open(id:string,event:React.MouseEvent<HTMLElement>){returnFocusRef.current=event.currentTarget;setSelectedId(id);setAnswer("");setMessage("")}
 async function saveAnswer(){if(!detail||detail.status!=="waiting"||!answer.trim())return;setSaving(true);setMessage("");try{const response=await fetch(`/api/questions/${detail.id}/answer`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({content:answer})}),result=await response.json().catch(()=>({}));if(!response.ok){if(response.status===409||["QUESTION_ALREADY_ANSWERED","QUESTION_CONFLICT"].includes(result.error)){setMessage("이미 답변이 등록된 질문입니다. 최신 상태를 다시 확인해 주세요.");await Promise.all([load(),loadDetail(detail.id)]);return}const errors:Record<string,string>={ANSWER_REQUIRED:"답변을 작성해 주세요.",PERSONAL_DATA_DETECTED:"답변에 개인정보로 보이는 내용이 포함되어 있습니다."};setMessage(errors[result.error]??"답변을 등록하지 못했습니다.");return}setAnswer("");setMessage("답변을 등록했습니다.");await Promise.all([load(),loadDetail(detail.id)])}finally{setSaving(false)}}
 async function moderateQuestion(isDeleted:boolean){if(!detail)return;if(isDeleted&&!window.confirm("이 질문을 삭제하시겠습니까?\n학생 Q&A에서는 더 이상 보이지 않으며, 관리자 페이지에서 다시 복구할 수 있습니다."))return;setSaving(true);setMessage("");try{const response=await fetch(`/api/admin/questions/${detail.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({isDeleted})}),result=await response.json().catch(()=>({}));if(!response.ok){setMessage(isDeleted?"질문을 삭제하지 못했습니다.":"질문을 복구하지 못했습니다.");return}setDetail(result.question);setMessage(isDeleted?"질문을 삭제했습니다.":"질문을 복구했습니다.");await load()}finally{setSaving(false)}}
 const pages=data?Array.from({length:Math.min(5,data.pagination.totalPages)},(_,index)=>Math.max(1,Math.min(data.pagination.totalPages-4,page-2))+index).filter(value=>value<=data.pagination.totalPages):[],hasFilters=Object.values(applied).some(Boolean);
 return <AdminShell activePath="/admin/questions" wide><main className="admin-dashboard-main admin-questions-workspace"><div className="admin-dashboard-title"><h1>Q&A 관리</h1><p>학생들이 동아리에 질문한 내용을 확인하고 답변을 관리할 수 있습니다.</p></div>
  {data&&<div className="admin-question-quick-filters" aria-label="질문 빠른 필터"><button type="button" className={!applied.status&&!applied.privacy&&!applied.deleted?"active":""} onClick={()=>quick("all")}>전체 <b>{data.summary.total}</b></button><button type="button" className={applied.status==="waiting"&&!applied.deleted?"active is-waiting":"is-waiting"} onClick={()=>quick("waiting")}>미답변 <b>{data.summary.statusCounts.waiting??0}</b></button><button type="button" className={applied.status==="answered"&&!applied.deleted?"active is-answered":"is-answered"} onClick={()=>quick("answered")}>답변완료 <b>{data.summary.statusCounts.answered??0}</b></button><button type="button" className={applied.privacy==="private"&&!applied.deleted?"active is-private":"is-private"} onClick={()=>quick("private")}>비공개 <b>{data.summary.privateCount}</b></button><button type="button" className={applied.deleted?"active is-deleted":"is-deleted"} onClick={()=>quick("deleted")}>삭제됨 <b>{data.summary.deletedCount}</b></button></div>}
  <form className="admin-question-filter-panel" onSubmit={submit}><label><span className="sr-only">질문 검색</span><input maxLength={120} placeholder="질문 제목 또는 내용 검색" value={filters.search} onChange={event=>setFilters({...filters,search:event.target.value})}/></label><label><span className="sr-only">동아리 필터</span><select value={filters.clubId} onChange={event=>setFilters({...filters,clubId:event.target.value})}><option value="">전체 동아리</option>{clubs.map(club=><option key={club.club_id} value={club.club_id}>{club.club_name}</option>)}</select></label><label><span className="sr-only">공개 상태</span><select value={filters.privacy} onChange={event=>setFilters({...filters,privacy:event.target.value})}><option value="">전체 공개 상태</option><option value="public">공개</option><option value="private">비공개</option></select></label><label><span className="sr-only">기간</span><select value={filters.period} onChange={event=>setFilters({...filters,period:event.target.value})}><option value="">전체 기간</option><option value="today">오늘</option><option value="7d">최근 7일</option><option value="30d">최근 30일</option></select></label><div className="admin-filter-buttons"><button type="button" onClick={reset}>초기화</button><button type="submit">검색</button></div></form>
  <section className="admin-question-list-panel">{error?<div className="admin-dashboard-empty">{error}</div>:!data?<div className="admin-dashboard-empty">질문 목록을 불러오는 중입니다.</div>:data.questions.length===0?<div className="admin-dashboard-empty">{data.summary.total===0&&!applied.deleted?"등록된 질문이 없습니다.":applied.status==="waiting"?"현재 미답변 질문이 없습니다.":hasFilters?"조건에 맞는 질문이 없습니다.":"등록된 질문이 없습니다."}</div>:<div className="admin-question-table" role="table" aria-label="질문 목록"><div className="admin-question-table-head" role="row"><span>질문 제목</span><span>동아리</span><span>작성자</span><span>상태</span><span>공개 여부</span><span>작성일</span><span>관리</span></div>{data.questions.map(question=><article className="admin-question-table-row" role="row" key={question.id}><strong data-label="질문 제목">{question.title}</strong><span data-label="동아리">{question.clubName}</span><span data-label="작성자">익명</span><span className="admin-question-status-stack" data-label="상태"><b className={`admin-question-badge state-${question.status}`}>{statusLabels[question.status]}</b>{question.isDeleted&&<b className="admin-question-badge is-deleted">삭제됨</b>}</span><span data-label="공개 여부"><b className={`admin-question-badge ${question.isPrivate?"is-private":"is-public"}`}>{question.isPrivate?"비공개":"공개"}</b></span><time data-label="작성일" dateTime={question.createdAt}>{formatDate(question.createdAt)}</time><button type="button" onClick={event=>open(question.id,event)}>상세 보기 <b aria-hidden="true">›</b></button></article>)}</div>}
   {data&&data.pagination.totalPages>1&&<nav className="admin-list-pagination" aria-label="질문 목록 페이지"><button type="button" disabled={page<=1} onClick={()=>setPage(page-1)} aria-label="이전 페이지">‹</button>{pages.map(number=><button type="button" className={number===page?"active":""} aria-current={number===page?"page":undefined} key={number} onClick={()=>setPage(number)}>{number}</button>)}<button type="button" disabled={page>=data.pagination.totalPages} onClick={()=>setPage(page+1)} aria-label="다음 페이지">›</button></nav>}
  </section>
  {selectedId&&<><button className="admin-drawer-backdrop" type="button" aria-label="질문 상세 닫기" onClick={close}/><aside className="admin-question-drawer" ref={drawerRef} tabIndex={-1} aria-label="질문 상세"><header><h2>질문 상세</h2><button type="button" aria-label="질문 상세 닫기" onClick={close}>×</button></header>{detailError?<div className="admin-drawer-loading">{detailError}</div>:!detail?<div className="admin-drawer-loading">질문 상세를 불러오는 중입니다.</div>:<><section className="admin-question-detail"><div><h3>{detail.title}</h3><span className="admin-question-status-stack"><b className={`admin-question-badge state-${detail.status}`}>{statusLabels[detail.status]}</b>{detail.isDeleted&&<b className="admin-question-badge is-deleted">삭제됨</b>}</span></div><p className="admin-question-meta"><span>{detail.clubName}</span><span>익명</span><time dateTime={detail.createdAt}>{formatDate(detail.createdAt)}</time><b className={`admin-question-badge ${detail.isPrivate?"is-private":"is-public"}`}>{detail.isPrivate?"비공개":"공개"}</b></p><h4>질문 내용</h4><p className="admin-question-content">{detail.content}</p></section>{detail.answer&&<section className="admin-question-answer"><h3>기존 답변</h3><small>{detail.answer.role} · {formatDate(detail.answer.createdAt)}</small><p>{detail.answer.content}</p></section>}{detail.status==="waiting"&&!detail.isDeleted&&<section className="admin-question-compose"><h3>답변 작성</h3><label><span className="sr-only">답변 내용</span><textarea maxLength={5000} placeholder="학생에게 전달할 답변을 작성해 주세요." value={answer} onChange={event=>setAnswer(event.target.value)}/><small>{answer.length} / 5000</small></label>{message&&<p className={message.includes("등록했습니다")?"form-success":"form-error"} role="status">{message}</p>}<div><button type="button" onClick={close}>취소</button><button type="button" disabled={saving||!answer.trim()} onClick={saveAnswer}>{saving?"등록 중…":"답변 등록"}</button></div></section>}<section className="admin-question-moderation"><h3>질문 관리</h3>{message&&<p className={message.includes("했습니다")?"form-success":"form-error"} role="status">{message}</p>}<button className={detail.isDeleted?"restore":"delete"} type="button" disabled={saving} onClick={()=>moderateQuestion(!detail.isDeleted)}>{detail.isDeleted?"질문 복구":"질문 삭제"}</button></section></>}</aside></>}
 </main></AdminShell>
}
