"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import AdminShell from "../AdminShell";

type Application={id:string;applicationNumber:string;studentName:string|null;studentNumber:string|null;userAlias:string;clubId:string;clubName:string;status:string;submittedAt:string;updatedAt:string;reviewedAt:string|null};
type Detail=Application&{motivation:string;interestArea:string|null;careerInterest:string;experience:string;additionalMessage:string|null;cancelledAt:string|null;reviewComment:string|null};
type Club={club_id:string;club_name:string};
type Payload={applications:Application[];pagination:{page:number;pageSize:number;total:number;totalPages:number};summary:{total:number;statusCounts:Record<string,number>}};
type Filters={status:string;clubId:string;search:string;sort:string;startDate:string;endDate:string};
const labels:Record<string,string>={submitted:"신청 완료",under_review:"검토 중",waiting:"검토 대기",approved:"승인",rejected:"반려",cancelled:"취소"};
const nextStates:Record<string,string[]>={submitted:["under_review","approved","rejected"],under_review:["waiting","approved","rejected"],waiting:["approved","rejected"],approved:[],rejected:[],cancelled:[]};
const initialFilters:Filters={status:"",clubId:"",search:"",sort:"newest",startDate:"",endDate:""};
const formatDate=(value:string)=>new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));
const grade=(number:string|null)=>number&&/^[1-3]/.test(number)?`${number.charAt(0)}학년`:"학년 미등록";

function DetailIcon({type}:{type:string}){const props={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(type==="target")return <svg {...props}><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="m15 9 5-5m-3 0h3v3"/></svg>;if(type==="career")return <svg {...props}><circle cx="12" cy="12" r="8"/><path d="m15 9-2 4-4 2 2-4 4-2Z"/></svg>;if(type==="experience")return <svg {...props}><path d="M5 5h14v15H5zM9 3h6v4H9z"/><path d="m9 13 2 2 4-4"/></svg>;if(type==="message")return <svg {...props}><path d="M4 4h16v13H8l-4 4V4Z"/><path d="M8 9h8m-8 4h6"/></svg>;return <svg {...props}><path d="M9 3h6l1 3h3v15H5V6h3l1-3Z"/><circle cx="12" cy="11" r="2.5"/><path d="M8 18a4 4 0 0 1 8 0"/></svg>}

export default function AdminApplicationsClient(){
 const[data,setData]=useState<Payload|null>(null),[clubs,setClubs]=useState<Club[]>([]),[error,setError]=useState(""),[filters,setFilters]=useState(initialFilters),[applied,setApplied]=useState(initialFilters),[page,setPage]=useState(1);
 const[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null),[detailError,setDetailError]=useState(""),[nextStatus,setNextStatus]=useState(""),[reviewComment,setReviewComment]=useState(""),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const drawerRef=useRef<HTMLElement>(null),returnFocusRef=useRef<HTMLElement|null>(null);
 const load=useCallback(async()=>{const params=new URLSearchParams({...applied,page:String(page),pageSize:"20"}),response=await fetch(`/api/admin/applications?${params}`,{cache:"no-store"});if(!response.ok){setError(response.status===403?"관리자 권한이 없습니다.":"신청 목록을 불러오지 못했습니다.");return}setError("");setData(await response.json())},[applied,page]);
 const loadDetail=useCallback(async(id:string)=>{setDetail(null);setDetailError("");const response=await fetch(`/api/admin/applications/${id}`,{cache:"no-store"});if(!response.ok){setDetailError("신청 상세 정보를 불러오지 못했습니다.");return}const item=(await response.json()).application as Detail;setDetail(item);setNextStatus(nextStates[item.status]?.[0]??"");setReviewComment(item.reviewComment??"")},[]);
 const closeDrawer=useCallback(()=>{setSelectedId(null);setDetail(null);setMessage("");setTimeout(()=>returnFocusRef.current?.focus(),0)},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{fetch("/api/clubs").then(response=>response.json()).then(result=>setClubs(result.clubs??[])).catch(()=>{})},[]);
 useEffect(()=>{if(!selectedId)return;void loadDetail(selectedId);drawerRef.current?.focus();const close=(event:KeyboardEvent)=>{if(event.key==="Escape")closeDrawer()};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[selectedId,loadDetail,closeDrawer]);
 function search(event:FormEvent){event.preventDefault();setPage(1);setApplied(filters)}
 function reset(){setFilters(initialFilters);setApplied(initialFilters);setPage(1)}
 function quickStatus(status:string){const next={...filters,status};setFilters(next);setApplied(next);setPage(1)}
 function openDrawer(id:string,event:React.MouseEvent<HTMLElement>){returnFocusRef.current=event.currentTarget;setSelectedId(id);setMessage("")}
 async function save(){if(!selectedId||!nextStatus)return;setSaving(true);setMessage("");try{const response=await fetch(`/api/admin/applications/${selectedId}/status`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:nextStatus,reviewComment})}),result=await response.json().catch(()=>({}));if(!response.ok){const errors:Record<string,string>={INVALID_STATUS_TRANSITION:"현재 상태에서는 선택한 상태로 변경할 수 없습니다.",APPLICATION_CONFLICT:"다른 관리자가 먼저 변경했습니다. 목록과 상세 정보를 다시 확인해 주세요.",REVIEW_COMMENT_TOO_LONG:"검토 의견은 1000자 이하로 작성해 주세요."};setMessage(errors[result.error]??"변경 내용을 저장하지 못했습니다.");return}setMessage("변경 내용을 저장했습니다.");await Promise.all([load(),loadDetail(selectedId)])}finally{setSaving(false)}}
 const pages=data?Array.from({length:Math.min(5,data.pagination.totalPages)},(_,index)=>Math.max(1,Math.min(data.pagination.totalPages-4,page-2))+index).filter(value=>value<=data.pagination.totalPages):[];
 return <AdminShell activePath="/admin/applications" wide><main className="admin-dashboard-main admin-applications-workspace"><div className="admin-dashboard-title"><h1>신청 관리</h1><p>동아리 신청 내역을 확인하고 처리할 수 있습니다.</p></div>
  <form className="admin-application-filter-panel" onSubmit={search}><label><span>검색</span><div className="admin-search-combo"><select aria-label="검색 대상"><option>통합 검색</option></select><input maxLength={200} placeholder="학번, 이름, 신청 번호 또는 지원 동기" value={filters.search} onChange={event=>setFilters({...filters,search:event.target.value})}/></div></label><label><span>동아리</span><select value={filters.clubId} onChange={event=>setFilters({...filters,clubId:event.target.value})}><option value="">전체 동아리</option>{clubs.map(club=><option value={club.club_id} key={club.club_id}>{club.club_name}</option>)}</select></label><label><span>상태</span><select value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})}><option value="">전체 상태</option>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><fieldset><legend>신청일</legend><label><span className="sr-only">시작일</span><input type="date" aria-label="시작일" value={filters.startDate} onChange={event=>setFilters({...filters,startDate:event.target.value})}/></label><i>~</i><label><span className="sr-only">종료일</span><input type="date" aria-label="종료일" value={filters.endDate} onChange={event=>setFilters({...filters,endDate:event.target.value})}/></label></fieldset><div className="admin-filter-buttons"><button type="button" onClick={reset}>초기화</button><button type="submit">검색</button></div></form>
  {data&&<div className="admin-status-chips" aria-label="상태 빠른 필터"><button className={!applied.status?"active":""} type="button" onClick={()=>quickStatus("")}>전체 <b>{data.summary.total}</b></button>{Object.entries(labels).map(([status,label])=><button className={applied.status===status?`active state-${status}`:`state-${status}`} type="button" key={status} onClick={()=>quickStatus(status)}>{label} <b>{data.summary.statusCounts[status]??0}</b></button>)}</div>}
  <section className="admin-application-list-panel"><header><strong>총 {data?.pagination.total??0}건</strong><label><span className="sr-only">정렬</span><select value={filters.sort} aria-label="신청 정렬" onChange={event=>{const next={...filters,sort:event.target.value};setFilters(next);setApplied(next);setPage(1)}}><option value="newest">신청일 최신순</option><option value="oldest">신청일 오래된순</option></select></label></header>
   {error?<div className="admin-dashboard-empty">{error}</div>:!data?<div className="admin-dashboard-empty">신청 목록을 불러오는 중입니다.</div>:data.applications.length===0?<div className="admin-dashboard-empty">조건에 맞는 신청이 없습니다.</div>:<div className="admin-application-table" role="table" aria-label="신청 목록"><div className="admin-application-table-head" role="row"><span>신청자</span><span>동아리</span><span>학년</span><span>상태</span><span>신청일</span><span>관리</span></div>{data.applications.map(item=><article className="admin-application-table-row" role="row" key={item.id}><div data-label="신청자"><strong>{item.studentName??"학생 정보 미등록"}</strong><small>{item.applicationNumber}</small></div><span data-label="동아리">{item.clubName}</span><span data-label="학년">{grade(item.studentNumber)}</span><span data-label="상태"><b className={`admin-status state-${item.status}`}>{labels[item.status]??item.status}</b></span><time data-label="신청일" dateTime={item.submittedAt}>{formatDate(item.submittedAt)}</time><button type="button" onClick={event=>openDrawer(item.id,event)}>상세 보기 <b aria-hidden="true">›</b></button></article>)}</div>}
   {data&&data.pagination.totalPages>1&&<nav className="admin-list-pagination" aria-label="신청 목록 페이지"><button type="button" disabled={page<=1} onClick={()=>setPage(page-1)} aria-label="이전 페이지">‹</button>{pages.map(number=><button type="button" className={number===page?"active":""} aria-current={number===page?"page":undefined} key={number} onClick={()=>setPage(number)}>{number}</button>)}<button type="button" disabled={page>=data.pagination.totalPages} onClick={()=>setPage(page+1)} aria-label="다음 페이지">›</button></nav>}
  </section>
  {selectedId&&<><button className="admin-drawer-backdrop" type="button" aria-label="신청 상세 닫기" onClick={closeDrawer}/><aside className="admin-application-drawer" ref={drawerRef} tabIndex={-1} aria-label="신청 상세 정보"><header><h2>신청 상세 정보</h2><button type="button" aria-label="신청 상세 닫기" onClick={closeDrawer}>×</button></header>{detailError?<div className="admin-drawer-loading">{detailError}</div>:!detail?<div className="admin-drawer-loading">신청 내용을 불러오는 중입니다.</div>:<><section className="admin-drawer-club"><div><strong>{detail.clubName}</strong><time dateTime={detail.submittedAt}>신청일 {formatDate(detail.submittedAt)}</time></div><b className={`admin-status state-${detail.status}`}>{labels[detail.status]??detail.status}</b><article><span><DetailIcon type="student"/></span><div><h3>{detail.studentName??"학생 정보 미등록"} <small>({grade(detail.studentNumber)})</small></h3><p>학번 {detail.studentNumber??"미등록"}</p><p>신청 상태 <b>{labels[detail.status]??detail.status}</b></p></div></article></section><section className="admin-drawer-answers"><h3>지원서 내용</h3>{[{label:"지원 동기",value:detail.motivation,type:"student"},{label:"관심 분야",value:detail.interestArea,type:"target"},{label:"희망 진로",value:detail.careerInterest,type:"career"},{label:"관련 활동 경험",value:detail.experience,type:"experience"},{label:"추가 전달 내용",value:detail.additionalMessage,type:"message"}].map(item=><article key={item.label}><span><DetailIcon type={item.type}/></span><div><strong>{item.label}</strong><p>{item.value||"작성하지 않음"}</p></div></article>)}</section><section className="admin-drawer-review"><h3>관리자 처리</h3>{nextStates[detail.status]?.length?<><fieldset><legend>상태 변경</legend>{nextStates[detail.status].map(value=><label key={value}><input type="radio" name="next-status" value={value} checked={nextStatus===value} onChange={()=>setNextStatus(value)}/><span>{labels[value]}</span></label>)}</fieldset><label className="admin-review-comment"><span>검토 의견</span><textarea maxLength={1000} placeholder="검토 의견을 입력하세요." value={reviewComment} onChange={event=>setReviewComment(event.target.value)}/><small>{reviewComment.length} / 1000</small></label>{message&&<p className={message.includes("저장했습니다")?"form-success":"form-error"} role="status">{message}</p>}<div className="admin-drawer-actions"><button type="button" onClick={closeDrawer}>취소</button><button type="button" disabled={saving||!nextStatus} onClick={save}>{saving?"저장 중…":"저장"}</button></div></>:<p className="admin-terminal-state">현재 상태에서는 추가 상태 변경을 할 수 없습니다.</p>}<Link href={`/admin/applications/${detail.id}`}>전체 상세 페이지에서 보기</Link></section></>}</aside></>}
 </main></AdminShell>;
}
