"use client";

import { FormEvent,useEffect,useState } from "react";
import { formatApplicationPeriodDate,type ApplicationPeriodSnapshot } from "../../lib/application-period";
import AdminShell from "../AdminShell";

const statusCopy={not_configured:["미설정","신청 기간을 설정해 주세요."],before:["신청 전","설정한 시작 시각부터 신청할 수 있습니다."],open:["신청 가능","현재 학생 신청을 받고 있습니다."],closed:["신청 종료","설정한 신청 기간이 종료되었습니다."]} as const;
const toInput=(value:string|null)=>{if(!value)return "";const parts=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));const get=(type:string)=>parts.find(part=>part.type===type)?.value??"";return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`};
const toSeoulIso=(value:string)=>`${value}:00+09:00`;

export default function ApplicationSettingsClient(){
 const[data,setData]=useState<ApplicationPeriodSnapshot|null>(null),[startAt,setStartAt]=useState(""),[endAt,setEndAt]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/admin/application-settings",{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();const result:ApplicationPeriodSnapshot=await response.json();setData(result);setStartAt(toInput(result.startAt));setEndAt(toInput(result.endAt))}).catch(()=>setError("신청 기간 설정을 불러오지 못했습니다.")).finally(()=>setLoading(false))},[]);
 async function submit(event:FormEvent){event.preventDefault();setMessage("");setError("");if(!startAt||!endAt)return setError("시작 시각과 종료 시각을 모두 입력해 주세요.");if(new Date(toSeoulIso(endAt))<=new Date(toSeoulIso(startAt)))return setError("종료 시각은 시작 시각보다 늦어야 합니다.");setSaving(true);try{const response=await fetch("/api/admin/application-settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({startAt:toSeoulIso(startAt),endAt:toSeoulIso(endAt)})}),result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error==="INVALID_APPLICATION_PERIOD"?"종료 시각은 시작 시각보다 늦어야 합니다.":"신청 기간을 저장하지 못했습니다.");return}setData(result);setStartAt(toInput(result.startAt));setEndAt(toInput(result.endAt));setMessage("신청 기간을 저장했습니다.")}catch{setError("신청 기간을 저장하지 못했습니다.")}finally{setSaving(false)}}
 const copy=data?statusCopy[data.status]:null;
 return <AdminShell activePath="/admin/application-settings"><main className="admin-dashboard-main application-settings-page"><div className="admin-dashboard-title"><h1>동아리 신청 기간 관리</h1><p>학생이 동아리 신청서를 제출할 수 있는 공통 기간을 설정합니다.</p></div><section className="application-settings-card">{loading?<div className="admin-dashboard-empty">신청 기간을 확인하는 중입니다.</div>:<><div className={`application-period-status state-${data?.status??"not_configured"}`}><span aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span><div><small>현재 상태</small><strong>{copy?.[0]}</strong><p>{copy?.[1]}</p></div></div>{data?.startAt&&data.endAt&&<dl className="application-period-current"><div><dt>신청 시작</dt><dd>{formatApplicationPeriodDate(data.startAt)}</dd></div><div><dt>신청 종료</dt><dd>{formatApplicationPeriodDate(data.endAt)}</dd></div></dl>}<form onSubmit={submit}><h2>신청 기간 설정</h2><p>모든 시각은 대한민국 표준시(Asia/Seoul) 기준입니다. 종료 시각은 신청할 수 없는 첫 시각입니다.</p><div><label>신청 시작 시각<input type="datetime-local" required value={startAt} onChange={event=>setStartAt(event.target.value)}/></label><label>신청 종료 시각<input type="datetime-local" required value={endAt} onChange={event=>setEndAt(event.target.value)}/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}<button type="submit" disabled={saving}>{saving?"저장 중…":"신청 기간 저장"}</button></form></>}</section></main></AdminShell>}
